const data = {
  logo: '/images/logo.svg',
  headerItems: [
    {
      _id: '1',
      icon: 'eva:pin-fill',
      description: 'Nearest Location',
      title: 'Abakaliki Mall',
    },
    {
      _id: '2',
      icon: 'fluent:call-24-filled',
      description: 'Call to Order',
      title: '+234 (0) 816 782 0935',
    },
    {
      _id: '3',
      icon: 'clarity:shopping-cart-solid',
      description: 'Shopping History',
      title: 'View Cart',
    },
  ],
  heroBoxes: [
    {
      _id: '1',
      brandIcon: 'nokiaIcon',
      brandName: 'Nokia 8.3 5G',
      heroText: 'Faster forward.',
      span: '5G speed. A14 Bionic, the fastest chip in a smartphone. And a Pro camera system that takes low-light photography to the next level - with even bigger jump on iPhone 11 Pro Max.',
      buttonLabel: 'Shop Now',
      buttonLink: '/',
      imageUrl: '/images/nokia7.2.png',
    },
    {
      _id: '2',
      brandIcon: '',
      brandName: 'haeir thermocool',
      heroText: 'Frozen Destinies.',
      span: '5G speed. A14 Bionic, the fastest chip in a smartphone. And a Pro camera system that takes low-light photography to the next level - with even bigger jump on iPhone 11 Pro Max.',
      buttonLabel: 'Shop Now',
      buttonLink: '/',
      imageUrl: '/images/42L-Freezer.png',
    },
    {
      _id: '3',
      brandIcon: 'twemoji:flag-for-flag-nigeria',
      brandName: 'Lab',
      heroText: 'Faster forward.',
      span: '5G speed. A14 Bionic, the fastest chip in a smartphone. And a Pro camera system that takes low-light photography to the next level - with even bigger jump on iPhone 11 Pro Max.',
      buttonLabel: 'Shop Now',
      buttonLink: '/',
      imageUrl: '/images/42L-Freezer.png',
    },
    {
      _id: '4',
      brandIcon: 'cib:samsung',
      brandName: 'Freezer',
      heroText: 'Faster forward.',
      span: '5G speed. A14 Bionic, the fastest chip in a smartphone. And a Pro camera system that takes low-light photography to the next level - with even bigger jump on iPhone 11 Pro Max.',
      buttonLabel: 'Shop Now',
      buttonLink: '/',
      imageUrl: '/images/42L-Freezer.png',
    },
    {
      _id: '5',
      brandIcon: 'simple-icons:nokia',
      brandName: 'iPhone11ProMax',
      heroText: 'Faster forward.',
      span: '5G speed. A14 Bionic, the fastest chip in a smartphone. And a Pro camera system that takes low-light photography to the next level - with even bigger jump on iPhone 11 Pro Max.',
      buttonLabel: 'Shop Now',
      buttonLink: '/',
      imageUrl: '/images/nokia7.2.png',
    },
    {
      _id: '6',
      brandIcon: 'ant-design:apple-filled',
      brandName: 'iPhone11ProMax',
      heroText: 'Faster forward.',
      span: '5G speed. A14 Bionic, the fastest chip in a smartphone. And a Pro camera system that takes low-light photography to the next level - with even bigger jump on iPhone 11 Pro Max.',
      buttonLabel: 'Shop Now',
      buttonLink: '/',
      imageUrl: '/images/iPhone-11-pro-max.png',
    },
  ],
  sideBoxes: [
    {
      _id: 'a',
      brandIcon: 'ant-design:apple-filled',
      brandName: 'Airpods Pro',
      title: 'The Best Ever',
      buttonLink: '/',
      buttonLabel: 'Shop Now',
      imageUrl: '/images/airpods-pro.png',
    },
    {
      _id: 'b',
      brandIcon: 'ant-design:apple-filled',
      brandName: 'Series 6',
      title: 'Are you Classy?',
      buttonLink: '/',
      buttonLabel: 'Shop Now',
      imageUrl: '/images/series-6.png',
    },
  ],
  trends: [
    {
      _id: '1',
      title: '32" plus TV',
      imageUrl: '/images/tv.png',
      link: '/shop/32-inches-tv',
    },
    {
      _id: '2',
      title: 'Blow Sapa Now!',
      imageUrl: '/images/fan.png',
      link: '/shop/blow-sapa',
    },
    {
      _id: '3',
      title: 'Electric Kettles',
      imageUrl: '/images/kettle.png',
      link: '/shop/kettles',
    },
    {
      _id: '4',
      title: 'Speakers',
      imageUrl: '/images/speakers.png',
      link: '/shop/speakers',
    },
    {
      _id: '5',
      title: 'Electric Irons',
      imageUrl: '/images/iron.png',
      link: '/shop/electric-irons',
    },
    {
      _id: '6',
      title: 'Freezer',
      imageUrl: '/images/freezer.png',
      link: '/shop/freezer',
    },
    {
      _id: '7',
      title: 'Microwave',
      imageUrl: '/images/microwave.png',
      link: '/shop/microwave',
    },
    {
      _id: '8',
      title: 'Dishwasher',
      imageUrl: '/images/dishwash.png',
      link: '/shop/dishwashers',
    },
    {
      _id: '9',
      title: 'Blenders',
      imageUrl: '/images/blend.png',
      link: '/shop/blenders',
    },
  ],
  smartGadgets: [
    {
      _id: '_1',
      image: '/images/Alexa.png',
      brandName: 'Amazon',
      linkLabel: 'Alexa Echo Dot 3 Smart speaker',
      linkUrl: '/product/1',
      price: '₦45,285',
    },
    {
      _id: '_2',
      image: '/images/bodycam.png',
      brandName: 'Motorolla',
      linkLabel: 'VB400 body worn smart camera',
      linkUrl: '/product/2',
      price: '₦75,860',
    },
    {
      _id: '_3',
      image: '/images/smart-lock.png',
      brandName: 'Kwikset',
      linkLabel: 'Smart door lock touchscreen',
      linkUrl: '/product/3',
      price: '₦56,000',
    },
    {
      _id: '_4',
      image: '/images/smart-lock.png',
      brandName: 'Amazon',
      linkLabel: 'Alexa Echo Dot 3 Smart speaker',
      linkUrl: '/product/4',
      price: '₦30,500',
    },
    {
      _id: '_5',
      image: '/images/smart-lock.png',
      brandName: 'Amazon',
      linkLabel: 'Alexa Echo Dot 3 Smart speaker',
      linkUrl: '/product/5',
      price: '₦21,900',
    },
  ],
  blogPosts: [
    {
      _id: '1',
      image: '/images/alexavsga.jpg',
      linkLabel: 'Alexa vs google Assistant',
      linkUrl: '/',
      date: '25 May, 2021',
      post: 'Alexa vs. Google Assistant is the Ali/Frazier of voice assistants. Both are backed by two of the heavyweights of tech, and both offer, on paper, many of the same',
    },
    {
      _id: '2',
      image: '/images/bodycam.jpg',
      linkLabel: 'Do I need a Body Cam?',
      linkUrl: '/',
      date: '06 Jun, 2021',
      post: 'Body camera is primarily seen as one way to inspire accountability in police forces around the country. Such visible displays of transparency affects the',
    },
    {
      _id: '3',
      image: '/images/airpod-max.jpg',
      linkLabel: 'Airpods Max or Nah!',
      linkUrl: '/',
      date: '07 July, 2021',
      post: "AirPods Max are Apple's high-end wireless over-ear headphones, featuring Noise Cancellation, Transparency Mode, Adaptive EQ, and spatial audio, in a range of",
    },
  ],
  apps: [
    { _id: '1', image: '/images/googlePlay.png', link: '/play-store' },
    { _id: '2', image: '/images/appStore.png', link: '/app-store' },
  ],
  Categories: [
    {
      _id: '1',
      title: 'Home and Kitchen',
      linkCat: '/shop/home-and-kitchen',
      image: '/images/home-and-kitchen-head.jpg',
      products: [
        {
          _id: '1',
          link: '/',
          label: 'Televsions',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          name: 'Home and Kitchen-1',
          brand: '',
          rating: 4.9,
          price: 750,
          discountedPrice: 700,
          numRatings: 14,
          numSales: 38,
          miniDescription: '',
          description: '',
          countInStock: 8,
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '2',
          link: '/',
          label: 'Microwaves',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          name: 'Home and Kitchen-1',
          brand: '',
          rating: 4.9,
          price: 750,
          discountedPrice: 700,
          numRatings: 12,
          numSales: 54,
          miniDescription: '',
          description: '',
          countInStock: 8,
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '3',
          link: '/',
          label: 'Washing Machines',
          thumbnail: '/images/microwave.png',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '4',
          link: '/',
          label: 'Dish Washers',
          thumbnail: '/images/microwave.png',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '5',
          link: '/',
          label: 'Electric speakers',
          thumbnail: '/images/microwave.png',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '6',
          link: '/',
          label: 'Electric kettles',
          thumbnail: '/images/microwave.png',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
      ],
    },
    {
      _id: '2',
      title: 'Phones and Tablets',
      linkCat: '/shop/home-and-kitchen',
      image: '/images/phone-and-tablets-head.jpg',

      products: [
        {
          _id: '1',
          link: '/',
          label: 'iPhone 11 Pro Max',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '2',
          link: '/',
          label: 'Nokia 8.3 5g',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '3',
          link: '/',
          label: 'Tecno Camon 17',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '4',
          link: '/',
          label: 'iPad Pro',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
      ],
    },
    {
      _id: '3',
      title: 'Laptops and Computers',
      linkCat: '/shop/laptops-and-computers',
      image: '/images/laptop-and-computers-head.jpg',

      products: [
        {
          _id: '1',
          link: '/',
          label: 'Televsions',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '2',
          link: '/',
          label: 'Microwaves',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '3',
          link: '/',
          label: 'Washing Machines',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '4',
          link: '/',
          label: 'Dish Washers',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '5',
          link: '/',
          label: 'Electric speakers',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
      ],
    },
    {
      _id: '4',
      title: 'Gaming and Headsets',
      linkCat: '/shop/gaming-and-headsets',
      image: '/images/gaming-and-headset-head.jpg',

      products: [
        {
          _id: '1',
          link: '/',
          label: 'Televsions',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '2',
          link: '/',
          label: 'Microwaves',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '3',
          link: '/',
          label: 'Washing Machines',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '4',
          link: '/',
          label: 'Dish Washers',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '5',
          link: '/',
          label: 'Electric speakers',
          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
      ],
    },
    {
      _id: '5',
      title: 'Electronics',
      linkCat: '/shop/electronics',
      image: '/images/home-and-kitchen-head.jpg',

      products: [
        {
          _id: '1',
          link: '/',
          label: 'Televsions',

          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '2',
          link: '/',
          label: 'Microwaves',

          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '3',
          link: '/',
          label: 'Washing Machines',

          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '4',
          link: '/',
          label: 'Dish Washers',

          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
        {
          _id: '5',
          link: '/',
          label: 'Electric speakers',

          thumbnail: '/images/home-and-kitchen-head.jpg',
          images: [
            { image: 'imageOne' },
            { image: 'imageTwo' },
            { image: 'imageThree' },
            { image: 'imageFour' },
            { image: 'imageFive' },
          ],
        },
      ],
    },
  ],
  Brands: [
    { _id: '1', name: 'Apple', link: '/' },
    { _id: '2', name: 'Nokia', link: '/' },
    { _id: '3', name: 'Samsung', link: '/' },
    { _id: '4', name: 'Philips', link: '/' },
    { _id: '5', name: 'Panasonic', link: '/' },
    { _id: '6', name: 'Century', link: '/' },
    { _id: '7', name: 'Itel', link: '/' },
    { _id: '8', name: 'Tecno', link: '/' },
  ],
};
export default data;
